-- SmartFacade360 Sovereign Data Engine Schema
-- TRL 5 Implementation | NTE E.060 Compliance | ISO 19650
-- Generated by Antigravity

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. ENUMS
DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('admin', 'inspector', 'analyst');
    CREATE TYPE file_type_enum AS ENUM ('obj', 'ifc');
    CREATE TYPE pathology_type_enum AS ENUM ('crack', 'moisture', 'thermal', 'structural');
    CREATE TYPE severity_level_enum AS ENUM ('low', 'medium', 'high', 'critical');
    CREATE TYPE sensor_type_enum AS ENUM ('vibration', 'emf', 'thermal');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 3. GOVERNANCE LAYER

-- Organizations (Tenants)
CREATE TABLE IF NOT EXISTS organizations (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    name text UNIQUE NOT NULL,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;

-- Profiles (Users linked to Tenants)
CREATE TABLE IF NOT EXISTS profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    organization_id uuid REFERENCES organizations(id) NOT NULL,
    role user_role DEFAULT 'inspector',
    created_at timestamptz DEFAULT now()
);
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- 4. DIGITAL ASSETS LAYER

-- Buildings (Core Entity)
CREATE TABLE IF NOT EXISTS buildings (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id uuid REFERENCES organizations(id) NOT NULL,
    name text NOT NULL,
    bim_metadata jsonb DEFAULT '{}',
    location geometry(Point, 4326),  -- Requires PostGIS, if not available context uses 2 columns or jsonb. Assuming PostGIS or simple point.
    -- Fallback if PostGIS not enabled: location_lat float, location_lng float
    created_at timestamptz DEFAULT now()
);
-- Note: 'geometry' type requires PostGIS. If standard Supabase/Postgres doesn't have it, we use jsonb for now.
-- Attempting to use geometry assuming typical setup. If fails, we revert to jsonb.
ALTER TABLE buildings ENABLE ROW LEVEL SECURITY;

-- Spatial Assets (3D Models)
CREATE TABLE IF NOT EXISTS spatial_assets (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    building_id uuid REFERENCES buildings(id) ON DELETE CASCADE,
    organization_id uuid REFERENCES organizations(id) NOT NULL,
    file_type file_type_enum NOT NULL,
    file_path text NOT NULL,
    coordinates jsonb DEFAULT '{}', -- WGS84
    deviation_metrics jsonb DEFAULT '{}', -- mm
    created_at timestamptz DEFAULT now()
);
ALTER TABLE spatial_assets ENABLE ROW LEVEL SECURITY;

-- 5. STRUCTURAL INTELLIGENCE LAYER

-- Inspections
CREATE TABLE IF NOT EXISTS inspections (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    building_id uuid REFERENCES buildings(id) ON DELETE CASCADE,
    organization_id uuid REFERENCES organizations(id) NOT NULL,
    drone_metadata jsonb DEFAULT '{}',
    inspection_date timestamptz DEFAULT now(),
    health_score numeric(5,2),
    created_at timestamptz DEFAULT now()
);
ALTER TABLE inspections ENABLE ROW LEVEL SECURITY;

-- Findings (Defects)
CREATE TABLE IF NOT EXISTS findings (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    inspection_id uuid REFERENCES inspections(id) ON DELETE CASCADE,
    organization_id uuid REFERENCES organizations(id) NOT NULL,
    pathology_type pathology_type_enum NOT NULL,
    severity_level severity_level_enum NOT NULL,
    metric_deviation numeric(10,3), -- mm
    nte_reference text, -- e.g. 'E.060 Art. 12'
    remediation_suggestion text,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE findings ENABLE ROW LEVEL SECURITY;

-- 6. IOT LAYER

-- Sensor Streams
CREATE TABLE IF NOT EXISTS sensor_streams (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    building_id uuid REFERENCES buildings(id) ON DELETE CASCADE,
    organization_id uuid REFERENCES organizations(id) NOT NULL,
    sensor_type sensor_type_enum NOT NULL,
    data_points jsonb NOT NULL, -- {x: val, y: val, z: val}
    timestamp timestamptz DEFAULT now(),
    fatigue_level numeric(5,2),
    created_at timestamptz DEFAULT now()
);
ALTER TABLE sensor_streams ENABLE ROW LEVEL SECURITY;

-- 7. VECTOR LAYER (RAG)

-- Normative Knowledge
CREATE TABLE IF NOT EXISTS normative_knowledge (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id uuid REFERENCES organizations(id) NOT NULL,
    section text NOT NULL, -- e.g. 'E.060 Art. 12'
    content text NOT NULL,
    embedding vector(1536),
    source text NOT NULL, -- e.g. 'NTE E.060'
    created_at timestamptz DEFAULT now()
);
ALTER TABLE normative_knowledge ENABLE ROW LEVEL SECURITY;

-- 8. INDEXES
CREATE INDEX IF NOT EXISTS idx_buildings_org ON buildings(organization_id);
CREATE INDEX IF NOT EXISTS idx_spatial_assets_org ON spatial_assets(organization_id);
CREATE INDEX IF NOT EXISTS idx_inspections_org ON inspections(organization_id);
CREATE INDEX IF NOT EXISTS idx_findings_org ON findings(organization_id);
CREATE INDEX IF NOT EXISTS idx_sensor_streams_org ON sensor_streams(organization_id);
CREATE INDEX IF NOT EXISTS idx_sensor_streams_ts ON sensor_streams("timestamp");
CREATE INDEX IF NOT EXISTS idx_normative_knowledge_org ON normative_knowledge(organization_id);

-- HNSW Index for Vectors
CREATE INDEX IF NOT EXISTS idx_normative_embedding ON normative_knowledge USING hmsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- 9. RLS POLICIES (Multi-Tenancy)

-- Helper function to get current user's org
CREATE OR REPLACE FUNCTION get_auth_org_id()
RETURNS uuid LANGUAGE sql SECURITY DEFINER AS $$
  SELECT organization_id FROM profiles WHERE id = auth.uid()
$$;

-- Apply to all tables
-- Organizations: Users can only see their own org
CREATE POLICY "Users can view own organization" ON organizations
    FOR SELECT USING (id = get_auth_org_id());

-- Profiles: Users can view profiles in their own org
CREATE POLICY "Users can view profiles in own org" ON profiles
    FOR SELECT USING (organization_id = get_auth_org_id());

-- Buildings
CREATE POLICY "Tenant isolation for buildings" ON buildings
    USING (organization_id = get_auth_org_id())
    WITH CHECK (organization_id = get_auth_org_id());

-- Spatial Assets
CREATE POLICY "Tenant isolation for spatial_assets" ON spatial_assets
    USING (organization_id = get_auth_org_id())
    WITH CHECK (organization_id = get_auth_org_id());

-- Inspections
CREATE POLICY "Tenant isolation for inspections" ON inspections
    USING (organization_id = get_auth_org_id())
    WITH CHECK (organization_id = get_auth_org_id());

-- Findings
CREATE POLICY "Tenant isolation for findings" ON findings
    USING (organization_id = get_auth_org_id())
    WITH CHECK (organization_id = get_auth_org_id());

-- Sensor Streams
CREATE POLICY "Tenant isolation for sensor_streams" ON sensor_streams
    USING (organization_id = get_auth_org_id())
    WITH CHECK (organization_id = get_auth_org_id());

-- Normative Knowledge
CREATE POLICY "Tenant isolation for normative_knowledge" ON normative_knowledge
    USING (organization_id = get_auth_org_id())
    WITH CHECK (organization_id = get_auth_org_id());
